data:
  augmentation: false
  dataset: fruits100_sample
  image_size: 224
logging:
  log_interval: 10
  save_model: false
model:
  architecture: resnet18
  num_classes: 100
  pretrained: false
training:
  batch_size: 8
  device: cpu
  epochs: 2
  learning_rate: 0.001
  num_workers: 0
